slcs:
  repo: https://github.com/ESGF/esgf-slcs-server.git
  version: slcs_env
  home: /usr/local/esgf-slcs-server
  dest: /usr/local/esgf-slcs-server/src/esgf-slcs-server
  static: /var/www/static
  wsgi_dir: /etc/slcs-wsgi-8888

idp_webapp:
  url: "{{ mirror.base }}/2.6/8/esgf-idp/esgf-idp.war"
  name: esgf-idp

myproxy:
  env: myproxy
  ca:
    dir: /var/lib/globus-connect-server/myproxy-ca
    cert: /var/lib/globus-connect-server/myproxy-ca/cacert.pem
    signing_policy: /var/lib/globus-connect-server/myproxy-ca/signing-policy
    key: /var/lib/globus-connect-server/myproxy-ca/cakey.pem
  scripts:
    dir: /esg/config/myproxy
    retriever: /esg/config/myproxy/retriever.py
    mapapp: /esg/config/myproxy/myproxy-certificate-mapapp
    extapp: /esg/config/myproxy/esg_attribute_callout_app