name: esgf-pub
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.8.28
  - cdat_info=8.2
  - cdtime=3.1.2
  - certifi=2019.9.11
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - cmor=3.5.0
  - cryptography=2.7
  - curl=7.65.3
  - decorator=4.4.0
  - distarray=2.12.2
  - enum34=1.1.6
  - esmf=7.1.0
  - esmpy=7.1.0
  - expat=2.2.6
  - functools32=3.2.3.2
  - future=0.17.1
  - g2clib=1.6.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - ipaddress=1.0.22
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.0.2
  - jupyter_core=4.5.0
  - krb5=1.16.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcdms=3.1.2
  - libcf=1.0.3
  - libcurl=7.65.3
  - libdrs=3.1.2
  - libdrs_f=3.1.2
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - mpi=1.0
  - mpich=3.2.1
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf-fortran=4.4.5
  - numpy=1.16.4
  - openssl=1.1.1d
  - pip=19.2.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - python=2.7.16
  - readline=7.0
  - setuptools=41.2.0
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - traitlets=4.3.2
  - udunits2=2.2.25
  - urllib3=1.24.2
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cdf2cim==0.3.3.0
    - cdms2==3.0.0
    - cf-python==3.0.1
    - cfdm==1.7.8
    - cfunits==3.2.2
    - esgcet==3.7.1
    - esgconfigparser==0.1.17
    - esgf-pyclient==0.2.1
    - esgfpid==0.7.14
    - esgprep==2.9.7
    - fuzzywuzzy==0.16.0
    - hurry-filesize==0.9
    - idna==2.7
    - jinja2==2.10.1
    - lockfile==0.12.2
    - lxml==4.4.1
    - markupsafe==1.1.1
    - myproxyclient==2.1.0
    - netcdf4==1.4.0
    - nose==1.3.7
    - pbr==5.4.3
    - pika==0.11.2
    - psutil==5.6.3
    - psycopg2==2.6.2
    - regrid2==3.0.0
    - requests==2.20.0
    - requests-cache==0.5.2
    - sqlalchemy==1.2.19
    - sqlalchemy-migrate==0.11.0
    - sqlparse==0.3.0
    - tempita==0.5.2
    - treelib==1.4.0
