name: esgf-pub
channels:
  - defaults
  - conda-forge
dependencies:
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - blas=1.1
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - cdat_info=8.1.1
  - cdtime=3.1.2
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - cmor=3.4.0
  - cryptography=2.6.1
  - curl=7.64.0
  - decorator=4.4.0
  - distarray=2.12.2
  - enum34=1.1.6
  - esmf=7.1.0
  - esmpy=7.1.0
  - expat=2.2.6
  - functools32=3.2.3.2
  - future=0.17.1
  - g2clib=1.6.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - ipaddress=1.0.22
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter_core=4.4.0
  - krb5=1.16.1
  - libcdms=3.1.2
  - libcf=1.0.2
  - libcurl=7.64.0
  - libdrs=3.1.2
  - libdrs_f=3.1.2
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libnetcdf=4.6.2
  - libopenblas=0.2.20
  - libpng=1.6.36
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - mpi=1.0
  - mpich=3.2.1
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf-fortran=4.4.5
  - numpy=1.15.2
  - openblas=0.2.20
  - openblas-devel=0.2.20
  - openssl=1.1.1b
  - ossuuid=1.6.2
  - pip=19.0.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - python=2.7.16
  - readline=7.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.27.2
  - tk=8.6.8
  - traitlets=4.3.2
  - udunits2=2.2.27
  - urllib3=1.24.1
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cdf2cim==0.3.3.0
    - cdms2==3.0.0
    - cf-python==2.3.3
    - cftime==1.0.3.4
    - esgcet==3.6.3
    - esgconfigparser==0.1.17
    - esgf-pyclient==0.2.1
    - esgfpid==0.7.12
    - esgprep==2.9.5
    - fuzzywuzzy==0.16.0
    - hurry-filesize==0.9
    - idna==2.7
    - jinja2==2.10
    - lockfile==0.12.2
    - lxml==4.3.2
    - markupsafe==1.1.1
    - myproxyclient==2.1.0
    - netcdf4==1.4.0
    - nose==1.3.7
    - pbr==5.1.3
    - pika==0.11.2
    - psutil==5.6.1
    - psycopg2==2.6.2
    - regrid2==3.0.0
    - requests==2.20.0
    - requests-cache==0.4.13
    - sqlalchemy==1.2.18
    - sqlalchemy-migrate==0.11.0
    - sqlparse==0.3.0
    - tempita==0.5.2
    - treelib==1.4.0
