- name: Clone esgf-utils repo
  git:
    repo: "{{ node_status.repo }}"
    dest: "{{ node_status.dest }}"
    force: yes
            
- name: Setup Node Status crontab
  cron:
    name: "install check_node_status"
    minute: "*/10"
    job: bash /usr/local/esgf-utils/node_status/node_status_check.sh

- name: Run the Node Status check script
  command: bash /usr/local/esgf-utils/node_status/node_status_check.sh

- name: Restart CoG
  command: /etc/cog-wsgi-8889/apachectl restart

- name: Restart wget_api
  command: /etc/esgf-wget-wsgi-8891/apachectl restart

