
# Load certificates Tomcat will trust
- name: Get trusted certificates
  get_url:
    url: "{{ tomcat.ts.url }}"
    dest: "{{ tomcat.ts.path }}"

- name: Get webcert hash
  command: openssl x509 -in {{ httpd.hostcert }} -hash -noout
  register: httpd_hostcert_hash

- name: Import web CA into Truststore
  java_cert:
    cert_path: "{{ httpd.hostcert }}"
    keystore_path: "{{ tomcat.ts.path }}"
    keystore_pass: "{{ tomcat.ts.pass }}"
    cert_alias: "{{ httpd_hostcert_hash.stdout.strip() }}"

# Load the hostkey and hostcert into the tomcat keystore
- name: Load host key
  no_log: true
  slurp:
    src: "{{ httpd.hostkey }}"
  register: keycontents

- name: Load host cert
  no_log: true
  slurp:
    src: "{{ httpd.hostcert }}"
  register: certcontents

- name: Create Keystore
  java_keystore:
    private_key: "{{ keycontents['content'] | b64decode }}"
    certificate: "{{ certcontents['content'] | b64decode }}"
    name: my_esgf_node
    dest: "{{ tomcat.ks.path }}"
    password: "{{ tomcat.ks.pass }}"
    force: yes
