
- name: solr Group
  group:
    name: solr

- name: solr User
  user:
    name: solr
    groups: solr

- name: solr Download
  register: solr_download
  unarchive:
    src: "{{ solr.src }}"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/{{ solr.root_dir }}"
  register: solr_download

- name: Remove {{ solr.path }} if new Solr downloaded
  when: solr_download is changed
  file:
    path: "{{ solr.path }}"
    state: absent

- name: Install solr
  when: solr_download is changed
  command: "cp -R /tmp/{{ solr.root_dir }} {{ solr.path }}"

- name: Install solr.in.sh
  template:
    src: solr.in.sh.j2
    dest: "{{ solr.path }}/bin/solr.in.sh"
    owner: solr
    group: solr

- name: Set solr ownership
  file:
    path: "{{ solr.path }}"
    owner: solr
    group: solr
    recurse: yes

- name: Download ESGF Solr Cores template
  unarchive:
    src: "{{ mirror.base }}/2.8/1/esg-search/solr-home.tar"
    dest: /tmp
    remote_src: yes
    creates: /tmp/solr-home
