
# Entry point for installing base components

- name: Install epel-release
  package:
    name: epel-release

- name: Install basic utilities
  package:
    name:
      - unzip
      - lsof
      - bind-utils
      - git
      - wget
      - gcc
      - openssl
      - openssl-devel
      - nss
      - curl
      - libcurl
    state: latest

- name: Import base tasks
  include_tasks: "{{ base_task }}.yml"
  loop:
    - postgres
    - properties
    - config
  loop_control:
    loop_var: base_task

- name: Include Globus Tools
  include_role:
    name: globus_tools

- name: Include Globus Certs
  include_role:
    name: globus_certs