
# Install the postgres server and devel files

- name: Ensure postgres is installed
  package:
    name: 
      - "{{ pkgs.postgres_devel }}"
      - "{{ pkgs.postgres_server }}"
      - "{{ pkgs.psgycopg2 }}"

- name: Initialize postgres
  command: service postgresql initdb
  args:
    creates: /var/lib/pgsql/data/*
    warn: no

- name: Install pg_hba.conf file
  copy:
    src: postgres/pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf

- name: Start postgres
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create db super user
  become: yes  
  become_user: postgres
  postgresql_user:
    name: "{{ all_db.users.super.name }}"
    password: "{{ all_db.users.super.pass }}"
    role_attr_flags: SUPERUSER

- name: Create ESGCET database
  become: yes  
  become_user: postgres
  postgresql_db:
    name: "{{ all_db.db }}"