- name: Create config directory
  file:
    path: "{{ esg.config.dir }}"
    state: directory

- name: Install properties
  template:
    src: base.properties.j2
    dest: "{{ esg.config.dir }}/esgf.properties"
    force: no
    mode: 0644

- name: Install config_type
  template:
    src: config_type.j2
    dest: "{{ esg.config.dir }}/config_type"
    force: no
    mode: 0644
