
- name: Install Globus IDP services
  yum:
    disable_gpg_check: yes
    name:
      - globus-connect-server-id-4.0.51
      - mhash
      - pam-pgsql

- name: myproxy Group
  when: is_6
  group:
    name: myproxy

- name: myproxy User
  when: is_6
  user:
    name: myproxy
    groups: myproxy

- name: Ensure the myproxy user can read the appropriate password file
  when: is_7
  user:
    name: myproxy
    groups: tomcat
    append: yes