name: cog
channels:
  - defaults
dependencies:
  - ca-certificates=2018.12.5
  - certifi=2018.11.29
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng
  - libstdcxx-ng
  - ncurses=6.1
  - openssl=1.1.1a
  - pip=18.1
  - python=2.7.15
  - readline=7.0
  - setuptools=40.6.3
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - zlib=1.2.11
  - pip:
    - bleach==1.4.2
    - chardet==3.0.4
    - django==1.10.4
    - django-contrib-comments==1.6.2
    - django-grappelli==2.8.1
    - django-openid-auth==0.7
    - django-simple-captcha==0.5.1
    - esgfpid==0.7.12
    - globusonline-transfer-api-client==0.10.18
    - html5lib==1.0b8
    - httplib2==0.12.0
    - idna==2.8
    - mod-wsgi==4.5.24
    - oauth2client==2.0.1
    - passlib==1.6.5
    - pika==0.11.2
    - pillow==5.4.1
    - psycopg2==2.7.7
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.4
    - pysqlite==2.8.1
    - python-magic==0.4.12
    - python-openid==2.2.5
    - requests==2.21.0
    - rsa==4.0
    - six==1.12.0
    - south==1.0.2
    - sqlalchemy==1.2.17
    - urllib3==1.24.1
prefix: /usr/local/conda/envs/cog
