name: schema-migrate
channels:
  - defaults
dependencies:
  - ca-certificates=2018.12.5
  - certifi=2018.11.29
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.1.1a
  - pip=18.1
  - python=2.7.15
  - readline=7.0
  - setuptools=40.6.3
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - zlib=1.2.11
  - pip:
    - decorator==4.3.2
    - pbr==5.1.2
    - psycopg2==2.7.7
    - six==1.12.0
    - sqlalchemy==1.3.0b2
    - sqlalchemy-migrate==0.12.0
    - sqlparse==0.2.4
    - tempita==0.5.3.dev0
prefix: /usr/local/conda/envs/schema-migrate
